In [1]:
# Act 1: Compute R

w, x, y, z = 0, 3, 1, 1

R = (w + x + y + z)
while R > 9:
    R = sum(map(int, str(R)))

print("R =", R)

R = 5

## Act 1: Mathematical Foundation

We compute the digital root of (0,3,1,1):

R = 5

This value will be used for simulation and system analysis.

In [3]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql+psycopg2://postgres:1234@localhost:5432/nyc_taxi"
)

try:
    with engine.connect() as conn:
        print("✅Connected successfully")
except Exception as e:
    print("❌ Error:", e)

✅ Connected successfully

In [4]:
import pandas as pd

df_apr = pd.read_parquet("yellow_tripdata_2025-04.parquet")
df_may = pd.read_parquet("yellow_tripdata_2025-05.parquet")
df_jun = pd.read_parquet("yellow_tripdata_2025-06.parquet")

df = pd.concat([df_apr, df_may, df_jun], ignore_index=True)

print("Data Shape:", df.shape)
df.head()

Data Shape: (12885358, 20)

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,store_and_fwd_flag,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
0,1,2025-04-01 00:47:06,2025-04-01 01:13:25,1.0,9.50,1.0,N,138,230,1,38.7,11.00,0.5,11.65,6.94,1.0,69.79,2.5,1.75,0.75
1,2,2025-04-01 00:27:35,2025-04-01 00:38:19,2.0,3.77,1.0,N,138,92,1,17.0,6.00,0.5,4.90,0.00,1.0,31.15,0.0,1.75,0.00
2,2,2025-04-01 00:24:07,2025-04-01 00:35:12,1.0,5.41,1.0,N,132,130,1,22.6,1.00,0.5,5.37,0.00,1.0,32.22,0.0,1.75,0.00
3,1,2025-04-01 00:56:30,2025-04-01 01:00:49,2.0,0.60,1.0,N,79,4,1,6.5,4.25,0.5,2.45,0.00,1.0,14.70,2.5,0.00,0.75
4,2,2025-04-01 00:00:17,2025-04-01 00:16:19,1.0,0.43,1.0,N,161,229,2,4.4,1.00,0.5,0.00,0.00,1.0,10.15,2.5,0.00,0.75

## Act 2: Raw Data

We combine April, May, and June datasets into one dataset.

This creates a continuous time window for analysis.

In [5]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 12885358 entries, 0 to 12885357
Data columns (total 20 columns):
 #   Column                 Dtype
---  ------                 -----
 0   VendorID               int32
 1   tpep_pickup_datetime   datetime64[us]
 2   tpep_dropoff_datetime  datetime64[us]
 3   passenger_count        float64
 4   trip_distance          float64
 5   RatecodeID             float64
 6   store_and_fwd_flag     str
 7   PULocationID           int32
 8   DOLocationID           int32
 9   payment_type           int64
 10  fare_amount            float64
 11  extra                  float64
 12  mta_tax                float64
 13  tip_amount             float64
 14  tolls_amount           float64
 15  improvement_surcharge  float64
 16  total_amount           float64
 17  congestion_surcharge   float64
 18  Airport_fee            float64
 19  cbd_congestion_fee     float64
dtypes: datetime64[us](2), float64(13), int32(3), int64(1), str(1)
memory usage: 1.8 GB

,VendorID,tpep_pickup_datetime,tpep_dropoff_datetime,passenger_count,trip_distance,RatecodeID,PULocationID,DOLocationID,payment_type,fare_amount,extra,mta_tax,tip_amount,tolls_amount,improvement_surcharge,total_amount,congestion_surcharge,Airport_fee,cbd_congestion_fee
count,1.288536e+07,12885358,12885358,9.730506e+06,1.288536e+07,9.730506e+06,1.288536e+07,1.288536e+07,1.288536e+07,1.288536e+07,1.288536e+07,1.288536e+07,1.288536e+07,1.288536e+07,1.288536e+07,1.288536e+07,9.730506e+06,9.730506e+06,1.288536e+07
mean,1.869057e+00,2025-05-17 06:43:35.693359,2025-05-17 07:00:56.561819,1.300557e+00,7.391721e+00,2.497717e+00,1.612719e+02,1.611392e+02,9.334597e-01,1.844492e+01,1.188643e+00,4.770479e-01,2.860194e+00,5.037709e-01,9.546712e-01,2.696244e+01,2.197597e+00,1.489467e-01,5.310559e-01
min,1.000000e+00,2009-01-01 00:20:39,2009-01-01 00:20:49,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,0.000000e+00,-1.777500e+03,-1.739000e+01,-2.174000e+01,-9.044000e+01,-1.481700e+02,-1.000000e+00,-1.793370e+03,-2.500000e+00,-1.750000e+00,-7.500000e-01
25%,2.000000e+00,2025-04-25 16:25:13,2025-04-25 16:46:34.250000,1.000000e+00,1.050000e+00,1.000000e+00,1.140000e+02,1.070000e+02,1.000000e+00,8.600000e+00,0.000000e+00,5.000000e-01,0.000000e+00,0.000000e+00,1.000000e+00,1.580000e+01,2.500000e+00,0.000000e+00,0.000000e+00
50%,2.000000e+00,2025-05-17 02:06:32,2025-05-17 02:20:20.500000,1.000000e+00,1.870000e+00,1.000000e+00,1.610000e+02,1.620000e+02,1.000000e+00,1.412000e+01,0.000000e+00,5.000000e-01,2.000000e+00,0.000000e+00,1.000000e+00,2.142000e+01,2.500000e+00,0.000000e+00,7.500000e-01
75%,2.000000e+00,2025-06-08 11:37:55,2025-06-08 11:55:10.750000,1.000000e+00,3.700000e+00,1.000000e+00,2.330000e+02,2.330000e+02,1.000000e+00,2.260000e+01,2.500000e+00,5.000000e-01,3.990000e+00,0.000000e+00,1.000000e+00,3.075000e+01,2.500000e+00,0.000000e+00,7.500000e-01
max,7.000000e+00,2025-06-30 23:59:59,2025-07-01 22:36:42,9.000000e+00,3.860884e+05,9.900000e+01,2.650000e+02,2.650000e+02,5.000000e+00,3.254780e+05,1.336000e+02,2.214000e+01,9.609400e+02,7.160500e+02,1.000000e+00,3.255285e+05,2.500000e+00,6.750000e+00,1.250000e+00
std,7.078702e-01,NaN,NaN,7.374017e-01,6.700548e+02,1.161676e+01,6.645231e+01,7.052725e+01,7.569940e-01,9.273454e+01,1.850769e+00,1.405195e-01,3.997990e+00,2.132820e+00,2.793336e-01,9.374036e+01,9.458683e-01,5.356171e-01,3.600657e-01

In [6]:
df_clean = df[
    (df['trip_distance'] > 0) &
    (df['fare_amount'] > 0) &
    (df['total_amount'] > 0) &
    (df['passenger_count'] > 0)
]

df_clean = df_clean[
    df_clean['tpep_dropoff_datetime'] > df_clean['tpep_pickup_datetime']
]

print("Original rows:", df.shape[0])
print("Cleaned rows:", df_clean.shape[0])

Original rows: 12885358
Cleaned rows: 9161338

## Defining a Real Trip

A trip is considered valid if:
- Distance > 0
- Fare > 0
- Passenger count > 0
- Dropoff time > pickup time

This definition affects all results and conclusions.

In [7]:
# Trip duration (minutes)
df_clean['trip_duration'] = (
    df_clean['tpep_dropoff_datetime'] - df_clean['tpep_pickup_datetime']
).dt.total_seconds() / 60

# Time features
df_clean['pickup_hour'] = df_clean['tpep_pickup_datetime'].dt.hour
df_clean['pickup_day'] = df_clean['tpep_pickup_datetime'].dt.day_name()

print("Feature Engineering Done")

Feature Engineering Done

In [8]:
correlation = df_clean[['trip_distance', 'tip_amount']].corr()
print("Correlation:\n", correlation)

Correlation:
                trip_distance  tip_amount
trip_distance       1.000000    0.023545
tip_amount          0.023545    1.000000

## Act 3: Behavioral Analysis

Hypothesis:
Longer trips result in higher tips.

We test this using correlation between distance and tip amount.

Alternative explanation:
Payment type may influence tipping behavior.

In [9]:
hourly = df_clean.groupby('pickup_hour').agg({
    'total_amount': 'mean',
    'trip_distance': 'mean',
    'VendorID': 'count'
}).rename(columns={'VendorID': 'trip_count'})

hourly = hourly.reset_index()

hourly.head()

   pickup_hour  total_amount  trip_distance  trip_count
0            0     31.349619       4.192361      241683
1            1     28.862996       3.783573      154753
2            2     26.242383       3.244860       99578
3            3     26.731568       3.985812       62634
4            4     34.377080       9.533442       41766

## Act 4: System Patterns

We aggregate data by hour to identify patterns in:
- Trip volume
- Fare trends
- Demand cycles

This helps determine system stability.

In [10]:
R = 5

df_clean['simulated_total'] = df_clean['total_amount'] * (1 + R/100)

print("Simulation Applied")

Simulation Applied

## Act 5: Simulation

We simulate a 5% fare increase.

This helps evaluate how the system responds to policy changes.

In [11]:
df_clean.to_sql(
    "taxi_clean",
    engine,
    if_exists="replace",
    index=False,
    chunksize=50000
)

print("Data uploaded to PostgreSQL")

Data uploaded to PostgreSQL

In [13]:
from sqlalchemy import text

query = text("SELECT COUNT(*) FROM taxi_clean")

with engine.connect() as conn:
    result = conn.execute(query)
    for row in result:
        print("Rows in DB:", row[0])

Rows in DB: 9161338

## Database Verification

In SQLAlchemy 2.x, SQL queries must be wrapped using the `text()` function.

This ensures the query is treated as an executable SQL statement.

We run a COUNT query to verify that the cleaned dataset has been successfully stored in PostgreSQL.